/**
 * Report model — formal incident reports generated by SKY.
 * A report is the human-readable, exportable artifact that captures
 * the full narrative of one or more incidents + recommended actions.
 */
import mongoose, { Schema, type InferSchemaType, type Model } from "mongoose";

const ReportSchema = new Schema(
  {
    reportId: { type: String, required: true, unique: true, index: true },
    title: { type: String, required: true },
    incidentIds: { type: [String], default: [] },
    summary: { type: String, default: "" },
    fullReport: { type: String, default: "" },
    recommendations: { type: [String], default: [] },
    riskProfile: {
      type: String,
      enum: ["low", "moderate", "high", "critical"],
      default: "moderate",
    },
    generatedBy: { type: String, default: "SKY-AI" },
    reviewedBy: { type: String, default: "" },
    status: {
      type: String,
      enum: ["draft", "final", "archived"],
      default: "draft",
      index: true,
    },
  },
  { timestamps: true }
);

export type ReportDoc = InferSchemaType<typeof ReportSchema> & {
  _id: mongoose.Types.ObjectId;
};

export const Report: Model<ReportDoc> =
  (mongoose.models.Report as Model<ReportDoc>) ||
  mongoose.model<ReportDoc>("Report", ReportSchema);
